exports.cardCategories = [
    "personality",
    "character",
    "activity",
    "object",
    "food",
    "nature",
    "place",
    "event",
    "art",
    "technology",
    "clothes",
    "movie",
    "tv-series",
    "book",
    "video-game",
    "painting",
    "theatre-play",
    "sculpture",
    "architecture",
    "music",
    "animal",
    "sport",
    "job",
];

exports.cardStatuses = ["to-guess", "discarded", "skipped", "guessed"];

exports.dummyCards = [
    { label: "Bill Gates", categories: ["personality"], difficulty: 2 },
    { label: "Barack Obama", categories: ["personality"], difficulty: 1 },
    { label: "Madonna", categories: ["personality"], difficulty: 2 },
    { label: "Will Smith", categories: ["personality"], difficulty: 1 },
    { label: "Peter Pan", categories: ["character"], difficulty: 1 },
    { label: "Pikachu", categories: ["character"], difficulty: 2 },
    { label: "Harry Potter", categories: ["character"], difficulty: 1 },
    { label: "Sherlock Holmes", categories: ["character"], difficulty: 1 },
    { label: "Hammer", categories: ["object"], difficulty: 1 },
    { label: "Cup", categories: ["object"], difficulty: 1 },
    { label: "Plane", categories: ["object"], difficulty: 2 },
    { label: "Table", categories: ["object"], difficulty: 2 },
    { label: "Waterfall", categories: ["nature"], difficulty: 3 },
    { label: "Oak", categories: ["nature"], difficulty: 2 },
    { label: "Star", categories: ["nature"], difficulty: 2 },
    { label: "Corsica", categories: ["place"], difficulty: 3 },
    { label: "Earth", categories: ["place"], difficulty: 2 },
    { label: "Hospital", categories: ["place"], difficulty: 2 },
    { label: "U.S.A", categories: ["place"], difficulty: 1 },
    { label: "The French Revolution", categories: ["event"], difficulty: 2 },
    { label: "The Birth of The Moon", categories: ["event"], difficulty: 3 },
    { label: "The Olympic Games", categories: ["event"], difficulty: 2 },
    { label: "French Football team becomes world champion", categories: ["event"], difficulty: 2 },
    { label: "Computer", categories: ["technology"], difficulty: 1 },
    { label: "Robot", categories: ["technology"], difficulty: 1 },
    { label: "Plane", categories: ["technology"], difficulty: 1 },
    { label: "Television", categories: ["technology"], difficulty: 1 },
    { label: "Sock", categories: ["clothes"], difficulty: 1 },
    { label: "Jeans", categories: ["clothes"], difficulty: 1 },
    { label: "Hat", categories: ["clothes"], difficulty: 1 },
    { label: "Coat", categories: ["clothes"], difficulty: 2 },
    { label: "Back To The Future", categories: ["movie"], difficulty: 2 },
    { label: "Cars", categories: ["movie"], difficulty: 2 },
    { label: "Dumbo", categories: ["movie"], difficulty: 1 },
    { label: "Spirited Away", categories: ["movie"], difficulty: 3 },
    { label: "Breaking Bad", categories: ["tv-series"], difficulty: 2 },
    { label: "Rick & Morty", categories: ["tv-series"], difficulty: 2 },
    { label: "The Office", categories: ["tv-series"], difficulty: 3 },
    { label: "One Piece", categories: ["tv-series"], difficulty: 3 },
    { label: "My Hero Academia", categories: ["book"], difficulty: 3 },
    { label: "Astérix", categories: ["book"], difficulty: 1 },
    { label: "Moby Dick", categories: ["book"], difficulty: 2 },
    { label: "The Odyssey", categories: ["book"], difficulty: 3 },
    { label: "Cat", categories: ["animal"], difficulty: 1 },
    { label: "Dog", categories: ["animal"], difficulty: 1 },
];