os: linux
dist: xenial
services: mongodb
language: node_js
node_js: 14
env:
- DB_NAME=times-up
install:
- npm install
- npm run lint
- npm test
notifications:
    slack: play-itgroupe:XemPiszUp35TjQVS1z6Ky8jW