name: Time's Up by Play-IT API Deployment on Production Server Workflow
on:
    push:
        branches:
            - master
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Setup GitHub repository 🔧
              uses: actions/checkout@v2
            - name: Setup NodeJS v14 ✨
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Setup MongoDB v5 🌿
              uses: supercharge/mongodb-github-action@1.6.0
              with:
                mongodb-version: '5'
            - name: Install project dependencies 📦
              run: npm install
            - name: Check and lint code 🔍
              run: npm run lint
            - name: Run tests ☑️
              run: npm test
            - name: Install SSH Key 🔑
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.TIMES_UP_PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
                known_hosts: ${{ secrets.TIMES_UP_KNOWN_HOSTS }}
            - name: Deploy to production server 🚀️
              run: ./deploy/deploy.sh master ${{ secrets.TIMES_UP_PRODUCTION_SERVER_SSH_USER }} ${{ secrets.PRODUCTION_SERVER_SSH_URL }}
            - name: Send Slack notification ✉️
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_USERNAME: GitHub Actions
                SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png?size=48'
                SLACK_WEBHOOK: ${{ secrets.TIMES_UP_SLACK_WEBHOOK }}
                SLACK_TITLE: ':rocket: Deployed to production server :tada:'